name: Project Health Check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build (Node.js v${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node: [8, 10, 12, 14, 16, 18]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ matrix.code }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Run build
        run: |
          npm install
          npm run build

  test:
    name: Unit Test (Node.js v${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node: [8, 10, 12, 14, 16, 18]
        
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ matrix.code }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Run test
        run: |
          npm install
          npm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
      
      - name: lint
        run: |
          npm install
          npm run lint