name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    environment: publish
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_AUTH_TOKEN}
          npm publish --access public
