name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Package and publish to github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
      - name: Package
        run: |
          npm pack
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.tgz
